version: '3.8'

services:
  app:
    #build: .
    image: ghcr.io/zizazar/bytescrap:master
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:example@db:5432/byte_scrap
    depends_on:
      - db

  db:
    image: postgres:17.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=byte_scrap
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data: